spring:
  application:
    name: streamguard-query-api

server:
  port: 8081

# RocksDB Configuration
# Path to the shared RocksDB database created by stream-processor
# Default: ./data/events.db (relative to project root)
# Override with ROCKSDB_PATH environment variable
rocksdb:
  path: ${ROCKSDB_PATH:./data/events.db}
  read-only: true

# OpenAI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:}
    model: gpt-4o-mini

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Logging
logging:
  level:
    com.streamguard: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
