package com.streamguard.queryapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Batch ML anomaly detection summary report.
 *
 * This model represents the summary statistics from the Spark ML batch processing pipeline.
 * Data is read from the anomaly_report.json file generated by the batch layer.
 */
public class AnomalyReport {

    @JsonProperty("total_users")
    private Integer totalUsers;

    @JsonProperty("anomalous_users")
    private Integer anomalousUsers;

    @JsonProperty("anomaly_rate")
    private Double anomalyRate;

    @JsonProperty("top_anomalies")
    private List<BatchAnomaly> topAnomalies;

    // Default constructor
    public AnomalyReport() {}

    // Full constructor
    public AnomalyReport(Integer totalUsers, Integer anomalousUsers,
                        Double anomalyRate, List<BatchAnomaly> topAnomalies) {
        this.totalUsers = totalUsers;
        this.anomalousUsers = anomalousUsers;
        this.anomalyRate = anomalyRate;
        this.topAnomalies = topAnomalies;
    }

    // Getters and setters
    public Integer getTotalUsers() {
        return totalUsers;
    }

    public void setTotalUsers(Integer totalUsers) {
        this.totalUsers = totalUsers;
    }

    public Integer getAnomalousUsers() {
        return anomalousUsers;
    }

    public void setAnomalousUsers(Integer anomalousUsers) {
        this.anomalousUsers = anomalousUsers;
    }

    public Double getAnomalyRate() {
        return anomalyRate;
    }

    public void setAnomalyRate(Double anomalyRate) {
        this.anomalyRate = anomalyRate;
    }

    public List<BatchAnomaly> getTopAnomalies() {
        return topAnomalies;
    }

    public void setTopAnomalies(List<BatchAnomaly> topAnomalies) {
        this.topAnomalies = topAnomalies;
    }

    @Override
    public String toString() {
        return "AnomalyReport{" +
                "totalUsers=" + totalUsers +
                ", anomalousUsers=" + anomalousUsers +
                ", anomalyRate=" + anomalyRate +
                ", topAnomalies=" + (topAnomalies != null ? topAnomalies.size() : 0) + " anomalies" +
                '}';
    }
}
