package com.streamguard.queryapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Batch ML anomaly detection result for a user.
 *
 * This model represents an anomaly detected by the Spark ML batch processing pipeline.
 * Data is read from Parquet files generated by the batch layer.
 */
public class BatchAnomaly {

    private String user;

    @JsonProperty("anomaly_score_normalized")
    private Double anomalyScore;

    @JsonProperty("total_events")
    private Integer totalEvents;

    @JsonProperty("avg_threat_score")
    private Double avgThreatScore;

    @JsonProperty("unique_ips")
    private Integer uniqueIps;

    @JsonProperty("failed_auth_rate")
    private Double failedAuthRate;

    @JsonProperty("is_anomaly")
    private Integer isAnomaly;

    // Default constructor
    public BatchAnomaly() {}

    // Full constructor
    public BatchAnomaly(String user, Double anomalyScore, Integer totalEvents,
                       Double avgThreatScore, Integer uniqueIps,
                       Double failedAuthRate, Integer isAnomaly) {
        this.user = user;
        this.anomalyScore = anomalyScore;
        this.totalEvents = totalEvents;
        this.avgThreatScore = avgThreatScore;
        this.uniqueIps = uniqueIps;
        this.failedAuthRate = failedAuthRate;
        this.isAnomaly = isAnomaly;
    }

    // Getters and setters
    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Double getAnomalyScore() {
        return anomalyScore;
    }

    public void setAnomalyScore(Double anomalyScore) {
        this.anomalyScore = anomalyScore;
    }

    public Integer getTotalEvents() {
        return totalEvents;
    }

    public void setTotalEvents(Integer totalEvents) {
        this.totalEvents = totalEvents;
    }

    public Double getAvgThreatScore() {
        return avgThreatScore;
    }

    public void setAvgThreatScore(Double avgThreatScore) {
        this.avgThreatScore = avgThreatScore;
    }

    public Integer getUniqueIps() {
        return uniqueIps;
    }

    public void setUniqueIps(Integer uniqueIps) {
        this.uniqueIps = uniqueIps;
    }

    public Double getFailedAuthRate() {
        return failedAuthRate;
    }

    public void setFailedAuthRate(Double failedAuthRate) {
        this.failedAuthRate = failedAuthRate;
    }

    public Integer getIsAnomaly() {
        return isAnomaly;
    }

    public void setIsAnomaly(Integer isAnomaly) {
        this.isAnomaly = isAnomaly;
    }

    @Override
    public String toString() {
        return "BatchAnomaly{" +
                "user='" + user + '\'' +
                ", anomalyScore=" + anomalyScore +
                ", totalEvents=" + totalEvents +
                ", avgThreatScore=" + avgThreatScore +
                ", uniqueIps=" + uniqueIps +
                ", failedAuthRate=" + failedAuthRate +
                ", isAnomaly=" + isAnomaly +
                '}';
    }
}
